## Authorizations
# Uncomment out the merging for each enviornment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# enviornment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=People,dc=oneops,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - cn=admins,ou=groups,dc=test,dc=com
    - cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["moreMembers", "cn=users,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    #objectClass: inetOrgPerson
    #authorizationRole: postsAdmin
    memberOf: DC=homeoffice,DC=Wal-Mart,DC=com

## Enviornments

development:
  host: <%= ENV['LDAP_HOST'] || 'localhost' %>
  port: 389
  attribute: <%= ENV['LDAP_ATTRIBUTE'] || 'uid' %>
  base: <%= ENV['LDAP_BASE'] || 'ou=People,dc=com' %>
  admin_user: cn=Manager,dc=oneops,dc=com
  admin_password: admin_password
  ssl: false
  # <<: *AUTHORIZATIONS

shared:
  host: <%= ENV['LDAP_HOST'] || 'honts0102.homeoffice.wal-mart.com' %>
  port: <%= ENV['LDAP_PORT'] || '3269' %>
  attribute: <%= ENV['LDAP_ATTRIBUTE'] || 'sAMAccountName' %>
  base: <%= ENV['LDAP_BASE'] || 'dc=wal-mart,dc=com' %>
  admin_user: <%= ENV['LDAP_ADMIN_USER'] || 'cn=admin,dc=test,dc=com' %>
  admin_password: <%= ENV['LDAP_ADMIN_PASSWORD'] || 'admin_password' %>
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: localhost
  port: 636
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: start_tls
  # <<: *AUTHORIZATIONS

enterprise:
  host: <%= ENV['LDAP_HOST'] || 'localhost' %>
  port: <%= ENV['LDAP_PORT'] || '636' %>
  attribute: <%= ENV['LDAP_ATTRIBUTE'] || 'sAMAccountName' %>
  base: <%= ENV['LDAP_BASE'] || 'ou=People,dc=com' %>
  admin_user: <%= ENV['LDAP_ADMIN_USER'] || 'cn=admin,dc=test,dc=com' %>
  admin_password: <%= ENV['LDAP_ADMIN_PASSWORD'] || 'admin_password' %>
  ssl: simple_tls
  # <<: *AUTHORIZATIONS
