# app/config/settings.yml

defaults: &defaults
  identity: <%= ENV['IDENTITY'] || '' %>
  support_auth: '<%= ENV['SUPPORT_AUTH'] %>'
  support_email: <%= ENV['SUPPORT_EMAIL'] %>

  max_admin_limit: <%= ENV['MAX_ADMIN_LIMIT'] %>
  global_admin_groups: '<%= ENV['GLOBAL_ADMIN_GROUPS'] %>'

  news_url: <%= ENV['NEWS_URL'] %>
  help_url: <%= ENV['HELP_URL'] %>
  feedback_url: <%= ENV['FEEDBACK_URL'] || 'https://oneops.slack.com/messages/feedback/' %>
  report_problem_url: <%= ENV['REPORT_PROBLEM_URL'] %>
  support_chat_url: <%= ENV['SUPPORT_CHAT_URL'] || 'https://oneops.slack.com/messages/help/' %>
  terms_of_service_url: <%= ENV['TERMS_OF_SERVICE_URL'] %>
  privacy_policy_url: <%= ENV['PRIVACY_POLICY_URL'] %>

  # Authentication types currently supported are database|ldap
  authentication: database

#   Omniauth configuration
#   omniauth:
#     github:
#       key: <%= ENV['GITHUB_KEY'] %>
#       secret: <%= ENV['GITHUB_SECRET'] %>
#       host: <%= ENV['GITHUB_HOST'] || 'github.com' %>
#     twitter:
#       key: <%= ENV['TWITTER_KEY'] %>
#       secret: <%= ENV['TWITTER_SECRET'] %>
#     linkedin:
#       key: <%= ENV['LINKEDIN_KEY'] %>
#       secret: <%= ENV['LINKEDIN_SECRET'] %>
#     google:
#       key: <%= ENV['GOOGLE_KEY'] %>
#       secret: <%= ENV['GOOGLE_SECRET'] %>

  # Controls the self-registration vs. invitation only registrations.
  # Only valid with authentication type 'database'.
  invitations: <%= ENV['SIGN_UP_INVITATION'] || 'false' %>

  # Controls the user confirmation requirements after registrations.
  confirmation: <%= ENV['SIGN_UP_CONFIRMATION'] || 'false' %>

  # Prompt for EULA acceptance on every login session if missing
  eula: <%= ENV['EULA_CONFIRMATION'] || 'true' %>

  # Mailer
  host: <%= ENV['OO_HOSTNAME'] || 'my.oneops.com' %>
  port: <%= ENV['OO_PORT'] || 443 %>
  protocol: <%= ENV['OO_PROTOCOL'] || 'https' %>

  mail_perform_deliveries: false
  mail_delivery_method: <%= ENV['MAIL_DELIVERY_METHOD'] || 'smtp' %>

  # JSON configuration of smtp settings as expected by action mailer, i.e.
  # export SMTP_SETTINGS="'{\"port\":1234, \"address\":\"blah\"}'"
  smtp_settings: <%= ENV['SMTP_SETTINGS'] || '' %>
  smtp_address: <%= ENV['SMTP_HOSTNAME'] || 'smtp' %>

  # Backend services
  cms_site: <%= ENV['CMS_SITE'] || 'http://cmsapi:8080/' %>
  transistor_site: <%= ENV['TRANSISTOR_SITE'] || ENV['CMS_SITE'] || 'http://cmsapi:8080/' %>
  metrics_site: <%= ENV['METRICS_SITE'] || 'http://cmsapi:8080/' %>
  metrics_context: <%= ENV['METRICS_CONTEXT'] || '/daq-1.0.0' %>
  events_site: <%= ENV['EVENTS_SITE'] || 'http://sensor:8080/' %>
  notifications_site: <%= ENV['NOTIFICATION_SITE'] || 'http://antenna:8080/' %>
  search_site: <%= ENV['SEARCH_SITE'] || 'http://search:9200/' %>
  log_site: <%= ENV['LOG_SITE'] || ENV['SEARCH_SITE'] || 'http://search:9200/' %>
  asset_url: <%= ENV['ASSET_URL'] %>

  cms_path_prefix: <%= ENV['CMS_PATH_PREFIX'] || '/adapter/rest' %>
  notification_hook:
    user: <%= ENV['NOTIFICATION_USER'] || 'admin' %>
    password: <%= ENV['NOTIFICATION_PASS'] || 'secret' %>

  # Use 'components/states' to use Sensor's old API (calculate counters on-the-fly).
  # Use 'components/states/count' to use Sensor's new optimized API (based on live counters).
  sensor_health_path: <%= ENV['SENSOR_HEALTH_PATH'] || 'components/states/count' %>

  # Use 'daq' to fetch logs from DAQ (old way).
  # Use 'es' to fetch logs from Elastic Search (new way).
  log_data_source: <%= ENV['LOG_DATA_SOURCE'] || 'es' %>

  policy_management: <%= ENV['POLICY_MANAGEMENT'] || 'true' %>
  check_policy_compliance: <%= ENV['CHECK_POLICY_COMPLIANCE'] || 'true' %>

  allow_cors: <%= ENV['ALLOW_CORS'] || 'true' %>
  session_inactivity_timeout: <%= ENV['SESSION_INACTIVITY_TIMEOUT'] || 30 %>

  show_cost: <%= ENV['SHOW_COST'] || 'false' %>

  allow_create_orgs: <%= ENV['ALLOW_CREATE_ORGS'] || 'true' %>

  pack_management_auth: '<%= ENV['PACK_MANAGEMENT_AUTH'] %>'

  # Metadata cache entries expiration in minutes
  md_cache_expiration_timeout: <%= ENV['MD_CACHE_EXPIRATION_TIMEOUT'] || (30 * 24 * 60) %>

  cms_http_timeout: <%= ENV['CMS_HTTP_TIMEOUT'] || 120 %>
  transistor_http_timeout: <%= ENV['TRANSISTOR_HTTP_TIMEOUT'] || 600 %>
  search_http_timeout: <%= ENV['SEARCH_HTTP_TIMEOUT'] || 10 %>
  sensor_http_timeout: <%= ENV['SENSOR_HTTP_TIMEOUT'] || 300 %>

  replace_by_global_admin_only: <%= ENV['REPLACE_BY_GLOBAL_ADMIN_ONLY'] || 'lb' %>

development: &development
  <<: *defaults

production: &production
  <<: *defaults
  mail_perform_deliveries: true

  # overrides
  invitations: <%= ENV['SIGN_UP_INVITATION'] || 'false' %>
  confirmation: <%= ENV['SIGN_UP_CONFIRMATION'] || 'true' %>

enterprise: &enterprise
  <<: *defaults
  mail_perform_deliveries: true

  # overrides
  authentication: ldap

  allow_create_orgs: <%= ENV['ALLOW_CREATE_ORGS'] || 'false' %>

  # additions
  ldap_domain: <%= ENV['LDAP_DOMAIN'] || nil %>
  ldap_email_attribute: <%= ENV['LDAP_EMAIL_ATTRIBUTE'] || 'mail' %>
  ldap_name_attribute: <%= ENV['LDAP_NAME_ATTRIBUTE'] || 'name' %>
